#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8

"""
UNTRANSLATE FASTA
James B. Pease
"""

import os
import sys
import argparse
from mixcore import fasta_iter, untranslate

_LICENSE = """
http://www.github.org/jbpease/mixtape
MixTAPE: Mix of Tools for Analysis in Phylogenetics and Evolution

This file is part of MixTAPE.

MixTAPE is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

MixTAPE is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MixTAPE.  If not, see <http://www.gnu.org/licenses/>.
"""


def generate_argparser():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        epilog=_LICENSE)
    parser.add_argument('protfasta', type=os.path.abspath,
                        help="input protein fasta file")
    parser.add_argument('nucfasta', type=os.path.abspath,
                        help="input nucleotide fasta file")
    parser.add_argument('--out', type=os.path.abspath,
                        default=sys.stdout, help="output fasta file")
    return parser


def main(arguments=None):
    arguments = arguments if arguments is not None else sys.argv[1:]
    parser = generate_argparser()
    args = parser.parse_args(args=arguments)
    nucleotide_sequences = {}
    for hdr, seq in fasta_iter(args.nucfasta):
        nucleotide_sequences[hdr] = seq
    for hdr, seq in fasta_iter(args.protfasta):
        if hdr not in nucleotide_sequences:
            raise RuntimeError("'{}' not found in nucleotide fasta".format(hdr))
        print(">{}\n{}".format(hdr, untranslate(seq, nucleotide_sequences[hdr])))
    return ''


if __name__ == '__main__':
    main()
